# RAG Document Processing Utility Configuration
# This file contains the main configuration for the document processing pipeline

# Document Processing Configuration
document_processing:
  # Supported document formats and their processing configurations
  supported_formats:
    pdf:
      parsers: [marker, pymupdf, unstructured]
      priority: 1
      chunking_strategy: semantic
      metadata_extraction: enhanced
    
    docx:
      parsers: [python-docx, unstructured]
      priority: 2
      chunking_strategy: structural
      metadata_extraction: basic
    
    txt:
      parsers: [unstructured]
      priority: 3
      chunking_strategy: fixed
      metadata_extraction: basic
    
    html:
      parsers: [beautifulsoup, unstructured]
      priority: 4
      chunking_strategy: structural
      metadata_extraction: basic
    
    md:
      parsers: [unstructured]
      priority: 5
      chunking_strategy: structural
      metadata_extraction: basic

  # Chunking configuration
  chunking:
    strategy: hybrid
    max_chunk_size: 1000
    min_chunk_size: 100
    overlap_size: 200
    semantic_threshold: 0.7

  # Metadata extraction configuration
  metadata:
    extraction_level: enhanced
    llm_provider: openai
    entity_recognition: true
    topic_extraction: true
    relationship_extraction: true
    summarization: true

  # Multimodal content processing
  multimodal:
    image_processing: true
    table_extraction: true
    math_processing: true
    ocr_engine: tesseract
    table_parser: camelot

  # Quality assurance configuration
  quality:
    enable_validation: true
    content_completeness: true
    structure_integrity: true
    metadata_accuracy: true
    embedding_quality: true
    performance_monitoring: true

  # Performance configuration
  performance:
    max_workers: 4
    batch_size: 10
    memory_limit: "2GB"
    timeout: 300

  # Output configuration
  output:
    output_dir: "output"
    chunk_dir: "chunks"
    metadata_dir: "metadata"
    embedding_dir: "embeddings"
    temp_dir: "temp"
    preserve_structure: true

  # Logging configuration
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/rag_prep.log"
    max_size: "10MB"
    backup_count: 5
